In [2]:
import numpy as np

In [3]:
list = [1,2,3,4,5]
np.array(list)

array([1, 2, 3, 4, 5])

In [4]:
two_d = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(two_d)

In [5]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [7]:
zero_mat = np.zeros((3,3))

In [8]:
zero_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
ones_mat = np.ones((3,3))
ones_mat

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.linspace(0,1,9).reshape(3,3)

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.rand(3,3)

array([[0.6499789 , 0.51870194, 0.90357087],
       [0.38414715, 0.745043  , 0.93923592],
       [0.53666727, 0.22184348, 0.58061443]])

In [12]:
rand_mat = np.random.randint(1,100,(3,3))
rand_mat

array([[30, 72, 20],
       [66, 99, 48],
       [58, 29, 48]])

In [13]:
rand_mat.reshape(9)

array([30, 72, 20, 66, 99, 48, 58, 29, 48])

In [14]:
rand_mat.max()

99

In [15]:
rand_mat.argmin()

2

In [16]:
matrix = matrix.reshape(9)

In [17]:
matrix.shape

(9,)

In [23]:
arr = np.random.randint(0,50,20)
arr

array([33,  7,  7, 36, 47, 45, 39, 18, 42,  4, 46, 15, 29,  7, 48,  1, 26,
       13, 38, 26])

In [24]:
arr[3]

36

In [25]:
arr[2:9]

array([ 7, 36, 47, 45, 39, 18, 42])

In [26]:
arr[6:]

array([39, 18, 42,  4, 46, 15, 29,  7, 48,  1, 26, 13, 38, 26])

In [27]:
arr[2:7] = 9
arr

array([33,  7,  9,  9,  9,  9,  9, 18, 42,  4, 46, 15, 29,  7, 48,  1, 26,
       13, 38, 26])

In [31]:
slice_arr  = arr[8:10]

In [33]:
slice_arr[:] = 90
slice_arr

array([90, 90])

In [34]:
arr

array([33,  7,  9,  9,  9,  9,  9, 18, 90, 90, 46, 15, 29,  7, 48,  1, 26,
       13, 38, 26])