In [1]:
import numpy as np

In [2]:
arr = np.random.randint(0,100,(5,5))
arr

array([[88, 72, 98, 72, 61],
       [93, 46, 63,  3, 53],
       [30, 63,  8, 21, 21],
       [67, 13, 63, 55, 29],
       [26,  8, 78, 83, 61]])

In [10]:
arr[:2,3:]

array([[72, 61],
       [ 3, 53]])

In [15]:
even_arr = arr%2 == 0

In [16]:
arr[even_arr]

array([88, 72, 98, 72, 46, 30,  8, 26,  8, 78])

In [17]:
arr[arr%3 == 0]

array([72, 72, 93, 63,  3, 30, 63, 21, 21, 63, 78])

In [18]:
arr*arr

array([[7744, 5184, 9604, 5184, 3721],
       [8649, 2116, 3969,    9, 2809],
       [ 900, 3969,   64,  441,  441],
       [4489,  169, 3969, 3025,  841],
       [ 676,   64, 6084, 6889, 3721]])

In [19]:
arr - arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
arr - 50

array([[ 38,  22,  48,  22,  11],
       [ 43,  -4,  13, -47,   3],
       [-20,  13, -42, -29, -29],
       [ 17, -37,  13,   5, -21],
       [-24, -42,  28,  33,  11]])

In [22]:
np.sin(arr)

array([[ 0.0353983 ,  0.25382336, -0.57338187,  0.25382336, -0.96611777],
       [-0.94828214,  0.90178835,  0.1673557 ,  0.14112001,  0.39592515],
       [-0.98803162,  0.1673557 ,  0.98935825,  0.83665564,  0.83665564],
       [-0.85551998,  0.42016704,  0.1673557 , -0.99975517, -0.66363388],
       [ 0.76255845,  0.98935825,  0.51397846,  0.96836446, -0.96611777]])

In [23]:
np.log(arr)

array([[4.47733681, 4.27666612, 4.58496748, 4.27666612, 4.11087386],
       [4.53259949, 3.8286414 , 4.14313473, 1.09861229, 3.97029191],
       [3.40119738, 4.14313473, 2.07944154, 3.04452244, 3.04452244],
       [4.20469262, 2.56494936, 4.14313473, 4.00733319, 3.36729583],
       [3.25809654, 2.07944154, 4.35670883, 4.41884061, 4.11087386]])